### ISSUE TITLE
Incorrect requirement `cygwin32-readline` for Cygwin x86_64

### ISSUE THREAD

**Issue by andrezstar** [rvm/rvm#2736]
Hi there,
Im trying to do all the stuff its said to be done here about the RVM and ruby setup, but when I do the 
-rvm get branch /features/cygwin
- rvm requirements

it always comes out with this:

``` bash
Installing required packages: patch, libyaml-devel, libyaml0_2, sqlite3, make, libtool, gcc, gcc-core, autoconf, automake, bison, m4, mingw64-i686-gcc, mingw64-x86_64-gcc, cygwin32-readline..
Error running 'requirements_cygwin_libs_install patch libyaml-devel libyaml0_2 sqlite3 make libtool gcc gcc-core autoconf automake bison m4 mingw64-i686-gcc mingw64-x86_64-gcc cygwin32-readline',
content of log /home/aramirez/.rvm/log/1395744907_ruby-1.9.3-p545/package_install_patch_libyaml-devel_libyaml0_2_sqlite3_make_libtool_gcc_gcc-core_autoconf_automake_bison_m4_mingw64-i686-gcc_mingw64-x86_64-gcc_cygwin32-readline.log
[2014-03-25 11:55:07] requirements_cygwin_libs_install
requirements_cygwin_libs_install ()
{
    typeset __packages_list __manager;
    if [[ "${_system_arch}" == "x86_64" ]]; then
        __manager="setup-x86_64.exe";
    else
        __manager="setup-x86.exe";
    fi;
    rvm_debug "__manager: ${__manager}";
    __packages_list="$*";
    ${__manager} -q -P "${__packages_list// /,}" || return $?
}
current path: /home/aramirez
PATH=/usr/local/bin:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/c/cygwin/usr/bin/mintty.exe:/usr/lib/lapack:/home/aramirez/.rvm/bin
command(16): requirements_cygwin_libs_install patch libyaml-devel libyaml0_2 sqlite3 make libtool gcc gcc-core autoconf automake bison m4 mingw64-i686-gcc mingw64-x86_64-gcc cygwin32-readline
++ typeset __packages_list __manager
++ [[ x86_64 == \x\8\6\_\6\4 ]]
++ __manager=setup-x86_64.exe
++ rvm_debug '__manager: setup-x86_64.exe'
++ ((  1  ))
++ rvm_pretty_print stderr
++ case "${rvm_pretty_print_flag:=auto}" in
++ case "${TERM:-dumb}" in
++ case "$1" in
++ [[ -t 2 ]]
++ return 1
++ printf %b '__manager: setup-x86_64.exe\n'
__manager: setup-x86_64.exe
++ __packages_list='patch libyaml-devel libyaml0_2 sqlite3 make libtool gcc gcc-core autoconf automake bison m4 mingw64-i686-gcc mingw64-x86_64-gcc cygwin32-readline'
++ setup-x86_64.exe -q -P patch,libyaml-devel,libyaml0_2,sqlite3,make,libtool,gcc,gcc-core,autoconf,automake,bison,m4,mingw64-i686-gcc,mingw64-x86_64-gcc,cygwin32-readline
-bash: setup-x86_64.exe: no se encontró la orden
++ return 127
Requirements installation failed with status: 127.
```

HELP PLEASE :(

**Comment by kotofos** [comment]
Same issue. I tried to install required packages via apt-cyg but there is no mingw64-i686-gcc, mingw64-x86_64-gcc packages. Only mingw64-i686-gcc-core, mingw64-x86_64-gcc-core. Is other than core gcc packages needed?

**Comment by akashi-dh** [comment]
@kotofos actually the requirement of ruby is mingw64-i686-gcc-core, mingw64-x86_64-gcc-core. So yeah, install them with other listed packages then you are good to go.

**Comment by arnotoma** [comment]
I have installed all the missing packages but I can't install "cygwin32-readline" package, it's as if the setup can't find it... So I still have this error (127)
++ __packages_list=cygwin32-readline
++ return 127
How can I install this package ?
Thx

**Comment by Mersion** [comment]
I have the same problem as arnotoma, but still i don't know what should I do with link you have sent to him. Requirements check doesn't have cygwin32-readline but below is this:  `then requirements_check cygwin32-readline` If I should clarify I can say that version of my Cygwin is 64.

**Comment by pkuczynski** [comment]
@NoemiElisa made a very good point. I just fixed it in master. Please update rvm (`rvm get master`) and try again....

**Comment by dillonraphael** [comment]
@pkuczynski I tried updating with `rvm get master`, but when I run `rvm install 2.3.1` I still get 

```
++ rvm_debug '__manager: detecting administrative permissions'
++ ((  0  ))
++ return 0
++ net session
++ '[' 0 -eq 0 ']'
++ __manager_admin_mode=
++ [[ x86_64 == \x\8\6\_\6\4 ]]
++ __manager=setup-x86_64.exe
++ rvm_debug '__manager: setup-x86_64.exe '
++ ((  0  ))
++ return 0
++ __packages_list=readline
++ setup-x86_64.exe -q -P readline
-bash: setup-x86_64.exe: command not found
++ return 127
Requirements installation failed with status: 127.
```

**Comment by Log1x** [comment]
I updated when `rvm get master` and attempted `rvm install 2.3.1` but still getting the same issue.

```
[~] → pact install readline
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache
Package readline is already installed, skipping
[~] → pact install cygwin32-readline
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing cygwin32-readline
Package cygwin32-readline not found or ambiguous name, exiting
[~] → rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: cygwin/unknown/i386/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for cygwin.
Installing requirements for cygwin.
Updating system.
Installing required packages: cygwin32-readline..
Error running 'requirements_cygwin_libs_install cygwin32-readline',
showing last 15 lines of /home/brandon/.rvm/log/1479233898_ruby-2.3.1/package_install_cygwin32-readline.log
++ rvm_debug '__manager: detecting administrative permissions'
++ ((  0  ))
++ return 0
++ net session
++ '[' 0 -eq 0 ']'
++ __manager_admin_mode=
++ [[ i386 == \x\8\6\_\6\4 ]]
++ __manager=setup-x86.exe
++ rvm_debug '__manager: setup-x86.exe '
++ ((  0  ))
++ return 0
++ __packages_list=cygwin32-readline
++ setup-x86.exe -q -P cygwin32-readline
/home/brandon/.rvm/scripts/functions/requirements/cygwin: line 26: setup-x86.exe: command not found
++ return 127
Requirements installation failed with status: 127.
```

Having the same issue. I can't find the cygwin32-readline package anywhere. I'm currently using Babun and tried manually looking for cygwin32-readline in setup-x86.exe but it does not show in the package list.

**Comment by pkuczynski** [comment]
@dillonraphael you have to add location of `setup-x86_64.exe` (the same which you used to install cygwin) to your path. And then it will work.

**Comment by pkuczynski** [comment]
@Log1x after brief search it seems that babun name this package simply `readline`. Could you please post output of `pact find readline`
