### ISSUE TITLE
Unable to install any version of rbx using rvm

### ISSUE THREAD

**Issue by hickscorp** [rvm/rvm#3617]
Hi,

I've been trying to install `rbx` using `rvm` for a few days. Not that I've struggled for a long time when I tried, but instead I've found myself waiting with no clue as if it was doing anything.

Basically:

```
$ rvm cleanup all && rvm install rbx
Cleaning up rvm archives
Cleaning up rvm repos
Cleaning up rvm src
Cleaning up rvm log
Cleaning up rvm tmp
Cleaning up rvm gemsets
Cleaning up rvm links
Cleanup done.
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.3.0@rubinius - #regenerating binstubs - please wait
Cloning from https://github.com/rubinius/rubinius.git, this may take a while depending on your connection - please wait
HEAD is now at e517891 Clarified what is covered by what license
From https://github.com/rubinius/rubinius
 * branch            master     -> FETCH_HEAD
Already up-to-date.
git checkout v2.5.8
Copying from repo to src path...
ruby-2.3.0@rubinius - #bundle install - please wait
```

After seeing the `#bundle install` line, nothing happens and `rvm` doesn't return. I've tried and let it sit overnight, but it won't complete. Looking at what might be happening shows:

```
$ ps aux | grep rvm
doodloo   4327  0.2  0.1 195136 27836 pts/6    Sl+  11:25   0:00 ruby /home/doodloo/.rvm/gems/ruby-2.3.0@rubinius/bin/bundle install                                                                      

$ ps aux | grep bundle
doodloo   4327  0.1  0.1 195136 27836 pts/6    Sl+  11:25   0:00 ruby /home/doodloo/.rvm/gems/ruby-2.3.0@rubinius/bin/bundle install                                                                      
```

Using `htop` with a filter set to `bundle` shows `0.0%` cpu usage, and I've tried with several versions of `rbx`, with no cigar so far.

I'm running `rvm 1.26.11 (master)` on an up-to-date `Xubuntu 15.10`. I'm successful installing various other rubies (`mri-2.x`, `jruby-9.0.4.0`).

**Comment by hickscorp** [comment]
Anything I could include to help diagnosing the issue?

**Comment by ioquatix** [comment]
Is anyone able to run tests on travis using rvm?

**Comment by pkuczynski** [comment]
@ioquatix how your comment is connected to this issue?

**Comment by ioquatix** [comment]
@pkuczynski It looks like travis use the similar command to install, and it fails in the same way, basically the same as 

```
rbx-2 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm rbx-2 do rvm gemset create ' first, or append '--create'.
```

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.

**Comment by adonespitogo** [comment]
I'm still getting this error in travis-ci. Here's my travis.yml file I copy and pasted straight from travis sample

```
language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-2
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
```

**Comment by pkuczynski** [comment]
Duplicate of #3287

**Comment by mathieujobin** [comment]
I am still having this issue on travis-ci

;(
