### ISSUE TITLE
Missing 'ruby' in 'rubygems_detect_ruby_lib_gem_path'.

### ISSUE THREAD

**Issue by jdashton** [rvm/rvm#3679]
I'm trying to install MRI 2.3.1 on current OS X (El Capitan), and getting the "Missing 'ruby'" message. I'm not sure what steps to take to help troubleshoot this further. This is using rvm head.

```
d11075:~ danielashton$ rvm cleanup all
Cleaning up rvm archives
Cleaning up rvm repos
Cleaning up rvm src
Cleaning up rvm log
Cleaning up rvm tmp
Cleaning up rvm gemsets
Cleaning up rvm links
Cleanup done.
d11075:~ danielashton$ rvmsudo rvm get head --auto-dotfiles
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: WARNING: unsafe ownership on configuration file `/Users/danielashton/.gnupg/gpg.conf'
gpg: Signature made Thu Jan 21 14:38:21 2016 EST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Turning on auto dotfiles mode.
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

# Daniel Ashton,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

RVM reloaded!
d11075:~ danielashton$ rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0  3006k      0  0:00:04  0:00:04 --:--:-- 3187k
ruby-2.3.1 - #extracting ruby-2.3.1 to /usr/local/rvm/src/ruby-2.3.1.................
ruby-2.3.1 - #configuring...........................................................
ruby-2.3.1 - #post-configuration...
ruby-2.3.1 - #compiling......................................................
ruby-2.3.1 - #installing..............
ruby-2.3.1 - #making binaries executable..
ruby-2.3.1 - #downloading rubygems-2.4.8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    395      0 --:--:-- --:--:-- --:--:--   396
100  437k  100  437k    0     0   385k      0  0:00:01  0:00:01 --:--:-- 2005k
ruby-2.3.1 - #extracting rubygems-2.4.8.................
ruby-2.3.1 - #removing old rubygems.....................................
ruby-2.3.1 - #installing rubygems-2.4.8.
Missing 'ruby' in 'rubygems_detect_ruby_lib_gem_path'.
ruby-2.3.1 - #gemset created /usr/local/rvm/gems/ruby-2.3.1@global
ruby-2.3.1 is not installed.
To install do: 'rvm install ruby-2.3.1'
ruby-2.3.1 is not installed.
To install do: 'rvm install ruby-2.3.1'
d11075:~ danielashton$

```

**Comment by jacob-carlborg** [comment]
I have the same problem. I reverted to RVM 1.25.0 (`rvm get 1.25.0`) and it fixed the problem.

**Comment by saizai** [comment]
Same problem. Reverting to RVM 1.25.0 did NOT fix the problem for me.

```bash
saizai@Sair:~$ rvm get stable --auto-dotfiles
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/saizai/.rvm/archives/rvm-installer.asc
gpg: Signature made Thu Jan 21 19:38:21 2016 GMT using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/saizai/.rvm/archives/rvm-installer'
Turning on auto dotfiles mode.
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
gpg: Signature made Tue Mar 29 14:49:47 2016 BST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/saizai/.rvm/archives/rvm-1.27.0.tgz'

Upgrading the RVM installation in /Users/saizai/.rvm/
    Removing rvm PATH line from /Users/saizai/.mkshrc /Users/saizai/.profile /Users/saizai/.bashrc /Users/saizai/.zshrc.
    Adding rvm PATH line to /Users/saizai/.profile /Users/saizai/.mkshrc /Users/saizai/.bashrc /Users/saizai/.zshrc.
    Removing rvm loading line from /Users/saizai/.profile /Users/saizai/.bash_profile /Users/saizai/.zlogin.
    Adding rvm loading line to /Users/saizai/.profile /Users/saizai/.bash_profile /Users/saizai/.zlogin.
    Updating libyaml in /Users/saizai/.rvm/usr to version 0.1.6, see https://github.com/rvm/rvm/issues/2594 ..................................................................................|
Upgrade of RVM in /Users/saizai/.rvm/ is complete.

# Sai,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:


  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/saizai/.bash_profile':

      source ~/.profile

  * It looks like some old stuff is laying around RVM, you can cleanup with: rvm cleanup all

  * No new notes to display.

RVM reloaded!
saizai@Sair:~$ rvm version
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
saizai@Sair:~$ rvm install ruby-2.3.0
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.
ruby-2.3.0 - #removing src/ruby-2.3.0......
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/opt/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Warning: DYLD_LIBRARY_PATH environment variable is set, this might interact with the compilation and ruby.
Installing Ruby from source to: /Users/saizai/.rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
ruby-2.3.0 - #extracting ruby-2.3.0 to /Users/saizai/.rvm/src/ruby-2.3.0.................
ruby-2.3.0 - #configuring.
ruby-2.3.0 - #post-configuration...
ruby-2.3.0 - #compiling..
ruby-2.3.0 - #installing..
ruby-2.3.0 - #making binaries executable..
ruby-2.3.0 - #downloading rubygems-2.4.8
ruby-2.3.0 - #extracting rubygems-2.4.8..................
ruby-2.3.0 - #removing old rubygems.....................................
ruby-2.3.0 - #installing rubygems-2.4.8.
Missing 'ruby' in 'rubygems_detect_ruby_lib_gem_path'.
ruby-2.3.0 - #gemset created /Users/saizai/.rvm/gems/ruby-2.3.0@global
ruby-2.3.0 is not installed.
To install do: 'rvm install ruby-2.3.0'
ruby-2.3.0 is not installed.
To install do: 'rvm install ruby-2.3.0'
saizai@Sair:~$ rvm list
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.

rvm rubies

=* rbx-2.5.8 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

saizai@Sair:~$ rvm get 1.25.0 --auto-dotfiles
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.

Hi there, it looks like you have requested updating rvm to version 1.25.0,
if your intention was ruby installation use instead: rvm install 1.25.0

Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/saizai/.rvm/archives/rvm-installer.asc
gpg: Signature made Thu Jan 21 19:38:21 2016 GMT using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/saizai/.rvm/archives/rvm-installer'
Turning on auto dotfiles mode.
Downloading https://github.com/rvm/rvm/archive/1.25.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.25.0/1.25.0.tar.gz.asc
curl: (22) The requested URL returned error: 404 Not Found

Could not download 'https://github.com/rvm/rvm/releases/download/1.25.0/1.25.0.tar.gz.asc'.
  curl returned status '22'.


Upgrading the RVM installation in /Users/saizai/.rvm/
    Removing rvm PATH line from /Users/saizai/.profile /Users/saizai/.bashrc /Users/saizai/.zshrc.
    Adding rvm PATH line to /Users/saizai/.profile /Users/saizai/.bashrc /Users/saizai/.zshrc.
    Removing rvm loading line from /Users/saizai/.profile /Users/saizai/.bash_profile /Users/saizai/.zlogin.
    Adding rvm loading line to /Users/saizai/.bash_profile /Users/saizai/.zlogin.
Upgrade of RVM in /Users/saizai/.rvm/ is complete.

# Sai,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:


  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/saizai/.bash_profile':

      source ~/.profile

  * It looks some old stuff is laying around RVM, you can cleanup with: rvm cleanup all


RVM reloaded!
saizai@Sair:~$ rvm version
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.

rvm 1.25.0 (1.25.0) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

saizai@Sair:~$ rvm install ruby-2.3.0
Warning, new version of rvm available '1.27.0', you are using older version '1.25.0'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/opt/local/etc/openssl/cert.pem' already are up to date.
Requirements installation successful.
Warning: DYLD_LIBRARY_PATH environment variable is set, this might interact with the compilation and ruby.
Installing Ruby from source to: /Users/saizai/.rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.0 - #already extracted to /Users/saizai/.rvm/src/ruby-2.3.0
ruby-2.3.0 - #configuring.
ruby-2.3.0 - #post-configuration.
ruby-2.3.0 - #compiling.
ruby-2.3.0 - #installing.
Retrieving rubygems-2.1.11
######################################################################## 100.0%
Extracting rubygems-2.1.11 ....
Removing old Rubygems files...
Installing rubygems-2.1.11 for ruby-2.3.0.
Installation of rubygems completed successfully.
.
Missing 'ruby' in 'rubygems_detect_ruby_lib_gem_path'.
ruby-2.3.0 - #gemset created /Users/saizai/.rvm/gems/ruby-2.3.0@global
ruby-2.3.0 is not installed.
To install do: 'rvm install ruby-2.3.0'
ruby-2.3.0 - #gemset created /Users/saizai/.rvm/gems/ruby-2.3.0
ruby-2.3.0 is not installed.
To install do: 'rvm install ruby-2.3.0'
ruby-2.3.0 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
cp: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/gem: No such file or directory
chmod: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/gem: No such file or directory
cp: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/irb: No such file or directory
chmod: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/irb: No such file or directory
cp: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/erb: No such file or directory
chmod: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/erb: No such file or directory
cp: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/ri: No such file or directory
chmod: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/ri: No such file or directory
cp: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/rdoc: No such file or directory
chmod: /Users/saizai/.rvm/rubies/ruby-2.3.0/bin/rdoc: No such file or directory
Install of ruby-2.3.0 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri
saizai@Sair:~$ rvm list
Warning! PATH is not properly set up, '/Users/saizai/.rvm/gems/rbx-2.5.8/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use rbx-2.5.8'.

rvm rubies

=* rbx-2.5.8 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

```

**Comment by saizai** [comment]
I've fixed this by `rvm implode` and complete re-installation. Fun times.

**Comment by jaimeiniesta** [comment]
Same here. I've tried `rvm implode` and complete reinstall of the stable version, and I get:

```
➔ rvm install ruby-2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/jaime/.rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0  7030k      0  0:00:02  0:00:02 --:--:-- 7032k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.1 - #extracting ruby-2.3.1 to /Users/jaime/.rvm/src/ruby-2.3.1....
ruby-2.3.1 - #configuring...........................................................
ruby-2.3.1 - #post-configuration.
ruby-2.3.1 - #compiling.....................................................
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/jaime/.rvm/log/1465914502_ruby-2.3.1/make.log
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2267:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
6 warnings and 9 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.
/Users/jaime/.rvm/bin/rvm: line 66: shell_session_update: command not found
```

**Comment by jacob-carlborg** [comment]
Actually, reverting to RVM 1.25.0 did _not_ help. I still have this problem.

**Comment by jacob-carlborg** [comment]
Ok, so the issue I had was to install `1.9.3-p194`. There are two issues here:

* `1.9.3-p194` failed to compile because the latest compiler is more pedantic when it comes to warnings, and some warnings are configured to be treated as errors

* RVM doesn't detect that the compilation failed

I found the actual compile error in the log file for make in: `~/.rvm/logs/xxxxxxxx_ruby-1.9.3-p194/make.log`. 

I managed to get it installed by suppressing the warning/errors: `CFLAGS='-w -Wno-error=shorten-64-to-32' rvm reinstall 1.9.3-p194`.

**Comment by jdashton** [comment]
The solution that worked for me was to force-link the OpenSSL Homebrew package, following the notes in the last post on this issue: https://github.com/rbenv/ruby-build/issues/898 After doing this I was able to simply `rvm install ruby-2.3.1` without setting any of the FLAGS variables.

The actual command was `brew link --overwrite openssl --force`

**Comment by pkuczynski** [comment]
We just uploaded 2.3.1 binaries for OSX El Capitan.

```
rvm get master
rvm install 2.3.1
```

should solve your problem.
