### ISSUE TITLE
https://get.rvm.io gives "bash: line 880: __rvm_print_headline: command not found"

### ISSUE THREAD

**Issue by diegopamio** [rvm/rvm#4068]
## Description

This problem is occurring today in both my production environment (Ubuntu) and in my development environment (Mac).

## Steps to reproduce

 1.  \curl -L https://get.rvm.io | bash -s stable --ruby=2.0.0 --autolibs=read-only

## Expected behavior

Install ruby 2.0.0 and rvm.

## Actual behavior

"bash: line 880: __rvm_print_headline: command not found"

## Environment info

None, as rvm was not even installed.

**Comment by diegopamio** [comment]
I've traced back the issue to a change made 5 hours ago: https://github.com/rvm/rvm/commit/d89dd65db58069fc8d942257485ce88dc0545f40

Any clue?

**Comment by szemek** [comment]
I got the same error cc @pkuczynski @mpapis

**Comment by devcfgc** [comment]
I'm getting the same error :disappointed:

**Comment by dragonchaser** [comment]
Same here

**Comment by ElvenSpellmaker** [comment]
The thing for me is, to use _stable_ it relies on the _master_  install script which seems to be wrong imo, changing this to: `curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/stable/binscripts/rvm-installer|  sudo bash -s stable` seems to work and that ensures you get the _stable_ installer and the _stable_ release... 🤔 

Imo `https://get.rvm.io` should point to the _stable_ installer and not master?

**Comment by devcfgc** [comment]
@ElvenSpellmaker's solution works like a charm :+1:

**Comment by diegopamio** [comment]
Good point @ElvenSpellmaker, for me the solution was to point to the previous commit. Buy your's looks like a better solution. And yes, I agree https://get.rvm.io should point to stable.

**Comment by pkuczynski** [comment]
Does `\curl -L https://get.rvm.io | bash` work for you?

**Comment by szemek** [comment]
@pkuczynski 

**ubuntu@ubuntu-xenial:~$ curl -L https://get.rvm.io | bash**

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    158      0  0:00:01  0:00:01 --:--:--   159
100 24063  100 24063    0     0  13559      0  0:00:01  0:00:01 --:--:--  301k
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Installing RVM to /home/ubuntu/.rvm/
    Adding rvm PATH line to /home/ubuntu/.profile /home/ubuntu/.mkshrc /home/ubuntu/.bashrc /home/ubuntu/.zshrc.
    Adding rvm loading line to /home/ubuntu/.profile /home/ubuntu/.bash_profile /home/ubuntu/.zlogin.
Installation of RVM in /home/ubuntu/.rvm/ is almost complete:

  * To start using RVM you need to run `source /home/ubuntu/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.
```

**ubuntu@ubuntu-xenial:~$ curl -sSL https://get.rvm.io | bash -s stable**

```
  Downloading https://github.com/rvm/rvm/archive/1.29.1.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Upgrading the RVM installation in /home/ubuntu/.rvm/
    RVM PATH line found in /home/ubuntu/.mkshrc /home/ubuntu/.profile /home/ubuntu/.bashrc /home/ubuntu/.zshrc.
    RVM sourcing line found in /home/ubuntu/.profile /home/ubuntu/.bash_profile /home/ubuntu/.zlogin.
Upgrade of RVM in /home/ubuntu/.rvm/ is complete.

# ubuntu,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.
```

**ubuntu@ubuntu-xenial:~$ curl -sSL https://get.rvm.io | bash -s stable --ruby=2.3.0**

```
Downloading https://github.com/rvm/rvm/archive/1.29.1.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Upgrading the RVM installation in /home/ubuntu/.rvm/
    RVM PATH line found in /home/ubuntu/.mkshrc /home/ubuntu/.profile /home/ubuntu/.bashrc /home/ubuntu/.zshrc.
    RVM sourcing line found in /home/ubuntu/.profile /home/ubuntu/.bash_profile /home/ubuntu/.zlogin.
Upgrade of RVM in /home/ubuntu/.rvm/ is complete.

# ubuntu,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

bash: line 880: __rvm_print_headline: command not found

**Comment by dcarastan** [comment]
The ruby installer regressed due to https://github.com/rvm/rvm/commit/d89dd65db58069fc8d942257485ce88dc0545f40#diff-36037c09d41eb6b50e82e55d585e4721. Here is a quick and dirty one-liner to get around it until an official fix arrives:
`curl -sSL https://get.rvm.io | grep -v __rvm_print_headline | bash -s stable --ruby`

**Comment by jaypeedevlin** [comment]
For clarity, is there anything wrong with leaving @dcarastan's line as is, or should I revert back to what I had originally once the fix is in.

**Comment by ElvenSpellmaker** [comment]
@jaypeedevlin I still think the workaround I mention [above](https://github.com/rvm/rvm/issues/4068#issuecomment-309416731) is better than @dcarastan's fix, mine uses the _stable_ installer, to install the _stable_ version.

As mentioned above, I believe `https:;//get.rvm.io` should point to the stable installer.

**Comment by jaypeedevlin** [comment]
Ahh, I understand your fix now, it didn't "click" on the first read for some reason...  Good thinking I'll patch our dockerfile again!

**Comment by pkuczynski** [comment]
I believe this issue has been already solved with the latest 1.29.2 release?

**Comment by ElvenSpellmaker** [comment]
@pkuczynski While you may have fixed the immediate issue I still think the default installer should point to _stable_ and not _master_ like I've mentioned above.

**Comment by aduffeck** [comment]
We are still seeing this issue in our docker builds btw. You can reproduce it using

```
docker run -it opensuse bash -c "zypper -n in curl tar which && gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && curl -sSL https://get.rvm.io | bash -s stable --ruby=2.3.1"
```
for example.

**Comment by premma** [comment]
I've got the same error mentioned initially in this issue today, just few minutes ago... While running command:

`curl -sSL https://get.rvm.io | sudo bash -s stable --ruby=2.3.3 `

The output follows:

`
Downloading https://github.com/rvm/rvm/archive/1.29.2.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc',
but no GPG software exists to validate it, skipping.
Creating group 'rvm'

Installing RVM to /usr/local/rvm/
Installation of RVM in /usr/local/rvm/ is almost complete:

  * First you need to add all users that will be using rvm to 'rvm' group,
    and logout - login again, anyone using rvm will be operating with `umask u=rwx,g=rwx,o=rx`.

  * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

# Administrator,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io
bash: line 880: __rvm_print_headline: command not found
`

The issue is still an issue 😸

**Comment by fifthposition** [comment]
I just got it today too.

**Comment by zw963** [comment]
@pkuczynski , still not work.

```sh
+ su -c '\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.3.4' rails51_with_yarn
Downloading https://github.com/rvm/rvm/archive/1.29.2.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Installing RVM to /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.rvm/
    Adding rvm PATH line to /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.profile /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.mkshrc /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.bashrc /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.zshrc.
    Adding rvm loading line to /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.profile /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.bash_profile /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.zlogin.
Installation of RVM in /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.rvm/ is almost complete:

  * To start using RVM you need to run `source /data_1/www/rails51_with_yarn/rails51_with_yarn_staging/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

# rails51_with_yarn,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io
bash: line 880: __rvm_print_headline: command not found

```

**Comment by zw963** [comment]
I downgrade from 1.29.2 downgrade to 1.27.0, still not worked

But, in same machine, another login user, once install 1.27.0 successful.

so, I think maybe exist something weird things make is not work again.

**Comment by zw963** [comment]
@pkuczynski , seperate to two step, it worked now.

previous not worked version:
```sh
su -l -c '\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.3.4' user_name
```

now worked version:
```sh
su -l -c "\curl -sSL https://get.rvm.io | bash -s stable" user_name
su -l -c "rvm install 2.3.4" user_name
```

**Comment by HenleyChiu** [comment]
I have nothing constructive to add, but just personally think it's insane the default URL is not pointed to the stable version. I also wished RVM gives us LOCAL installation instructions, that doesn't depend on downloading keys or packages online. This is essential for devops people as we don't want to spend every X months looking at these issues. Installing basic stuff like Ruby should be reproducible month after month, year after year, with no surprises. Leave surprises to birthday parties.

**Comment by ms1841** [comment]
@zw963 How does one find out what their username is? I am completely new to Dev-ops, dev-ops guy is gone, everything is on fire haha

**Comment by zw963** [comment]
@ms1841, `user_name` just a example, this usage is just for use in interactive script.
if you login to that use, just the command in the `" ... "`.

**Comment by hudsonmendes** [comment]
For those in need of a work around:
```bash 
curl -sSL https://get.rvm.io | sed -E s/\_rvm\_print\_headline/\_rvm\_version/ | bash -s stable --rails
```
This is to fix whatever was done here: 
[d89dd65](https://github.com/rvm/rvm/commit/d89dd65db58069fc8d942257485ce88dc0545f40), it was still breaking for me.

**Comment by elbarto132** [comment]
This issue still exists, but hudsonmendes' work around is working for me

**Comment by ElvenSpellmaker** [comment]
@elbarto132 Does the workaround I posted still work?

Using the _stable_ installer to install the _stable_ version of rvm seems a better otion to me than grepping the _master_ unstable installer?

https://github.com/rvm/rvm/issues/4068#issuecomment-309416731

**Comment by zepplen** [comment]
FYI I just hit this bug trying to install rvm on ubuntu 17.10 using the https://get.rvm.io endpoint. So you may want to re-open the issue.

**Comment by raelgc** [comment]
@zepplen same happens if you try, after implode rvm, install the [ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by zepplen** [comment]
I have not tried that, https://raw.githubusercontent.com/wayneeseguin/rvm/stable/binscripts/rvm-installer worked for me.

**Comment by aphofstede** [comment]
Same happened to me while provisioning 14.04 for an older project. Command was `curl -sSL https://get.rvm.io | bash -s stable --quiet-curl --ruby=2.1.10`.  The `sed -E s/\_rvm\_print\_headline/\_rvm\_version/` workaround above fixed it for me.

**Comment by sierrafayad** [comment]
Happens the same on Debian 9.1

**Comment by dialex** [comment]
Happens the same on Ubuntu, using Docker

**Comment by zw963** [comment]
@dialex , split to two step, it worked.

https://github.com/rvm/rvm/issues/4068#issuecomment-315112673

**Comment by ElvenSpellmaker** [comment]
Does the stable installer still work for you? https://github.com/rvm/rvm/issues/4068#issuecomment-309416731

**Comment by riccardoerra** [comment]
Tried just now and error still there. Fixed thanks to @ElvenSpellmaker and not need for `sudo`. I used:

```
\curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/stable/binscripts/rvm-installer | bash -s stable --ruby
```

**Comment by bilel-kedidi** [comment]
this works for me:
curl -sSL https://get.rvm.io | sed -E s/\_rvm\_print\_headline/\_rvm\_version/ | bash -s stable --rails

**Comment by franz-josef-kaiser** [comment]
To all of you who use the command piped through `sed`: You are doing a _temporary fix_ that is slow and will be obsolete once this is _really fixed_. Better just go with the 
`raw.githubusercontent.com` route for now as this points to the `stable` release. The main problem is that the _shortlink_ simply points to the wrong release.

**Comment by mpapis** [comment]
the error happens with `--ruby` or `--rails` flags only fixed in #4134

**Comment by ElvenSpellmaker** [comment]
As I keep saying, and as @franz-josef-kaiser agrees, the `get.rvm.io` should clearly point to the `stable` installer and not `master`. As per https://github.com/rvm/rvm/issues/4068#issuecomment-309416731

It's critical to have stable systems for Automation Infrastructure and using `master` isn't stable.

**Comment by mpapis** [comment]
@ElvenSpellmaker please open separate issue, this ticket was about a bug that was clearly not fixed, I reopened it to address the bug and it will be fixed with the PR I opened.

**Comment by ElvenSpellmaker** [comment]
@mpapis I've done so, thanks. 👍
